import AppKit
import Carbon.HIToolbox
@testable import Liquid_Voice_Debug
import XCTest

// Text delivery tests. Every test that writes a pasteboard uses a private, uniquely named
// one: nothing here may touch the user's real clipboard.
//
// Pasteboard hygiene tests are ported from altic-dev/FluidVoice's
// TypingServiceTransientPasteboardTests and PasteDeliveryCoordinatorTests
// (@b0d64436, @b1184755, @03477453, @a2d6ef32, @bbaedd94, @a3c896a7, @c0118882, @a1a65772,
// @caedd4ef, @788d04b6, @b1d14044, @adf0216e), adapted to Liquid Voice's serial paste
// session. The invariant tests at the bottom are Liquid Voice's own.

// MARK: - Temporary write and snapshot/restore

final class TypingServiceTransientPasteboardTests: XCTestCase {
    func testTemporaryPasteboardWriteCarriesText() {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeTemporaryText("hello world", sessionID: "session"))
        XCTAssertEqual(pasteboard.string(forType: .string), "hello world")
    }

    func testTemporaryPasteboardWriteIsMarkedForClipboardManagers() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeTemporaryText("hello world", sessionID: "session"))
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertTrue(types.contains(Self.transientType.rawValue), "temporary write must be marked Transient so clipboard managers skip it")
        XCTAssertTrue(types.contains(Self.autoGeneratedType.rawValue), "temporary write must be marked AutoGenerated so clipboard managers skip it")
        XCTAssertEqual(item.data(forType: Self.transientType)?.count, 0)
        XCTAssertEqual(item.data(forType: Self.autoGeneratedType)?.count, 0)
    }

    func testTemporaryPasteboardWriteCarriesSourceAndSession() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeTemporaryText("hello world", sessionID: "session"))
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertEqual(
            item.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.source")),
            Bundle.main.bundleIdentifier ?? "com.FluidApp.app"
        )
        XCTAssertEqual(item.string(forType: SystemPasteboardManager.sessionType), "session")
    }

    func testTemporaryPasteboardWriteIsConcealedButStillPasteable() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeTemporaryText("hello world", sessionID: "session"))
        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertTrue(
            item.types.contains(Self.concealedType),
            "temporary dictation must be concealed from clipboard history"
        )
        XCTAssertEqual(item.data(forType: Self.concealedType), Data())
        XCTAssertEqual(item.string(forType: .string), "hello world")
    }

    func testIntentionalClipboardWriteIsHistoryVisible() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        XCTAssertTrue(SystemPasteboardManager(pasteboard: pasteboard).writeIntentionalText("keep me"))

        let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let types = item.types.map(\.rawValue)
        XCTAssertEqual(item.string(forType: .string), "keep me")
        XCTAssertFalse(types.contains(Self.transientType.rawValue))
        XCTAssertFalse(types.contains(Self.autoGeneratedType.rawValue))
        XCTAssertFalse(types.contains(Self.concealedType.rawValue))
        XCTAssertFalse(types.contains { $0.hasSuffix(".PasteSession") })
    }

    func testSnapshotSkipsOversizedRepresentationsButKeepsTheRest() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let hugeType = NSPasteboard.PasteboardType("com.liquidvoice.tests.huge")
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(Data(count: SystemPasteboardManager.maximumRepresentationBytes + 1), forType: hugeType))
        XCTAssertTrue(item.setString("keep me", forType: .string))
        XCTAssertTrue(pasteboard.writeObjects([item]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.count, 1)
        XCTAssertEqual(snapshot.items.first?.representations.map(\.type), [.string])
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))
        XCTAssertEqual(pasteboard.string(forType: .string), "keep me")
        XCTAssertNil(pasteboard.data(forType: hugeType))
    }

    func testOversizedFilePayloadStillRestoresItsFilename() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let hugeType = NSPasteboard.PasteboardType("com.liquidvoice.tests.huge")
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setString("file:///tmp/Quarterly%20Report.mov", forType: .fileURL))
        XCTAssertTrue(item.setData(Data(count: SystemPasteboardManager.maximumRepresentationBytes + 1), forType: hugeType))
        XCTAssertTrue(pasteboard.writeObjects([item]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        XCTAssertEqual(pasteboard.string(forType: .fileURL), "file:///tmp/Quarterly%20Report.mov")
        XCTAssertEqual(pasteboard.string(forType: .string), "Quarterly Report.mov")
        XCTAssertNil(pasteboard.data(forType: hugeType))
    }

    func testSnapshotWithNothingSmallEnoughStillLetsThePasteProceed() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let hugeType = NSPasteboard.PasteboardType("com.liquidvoice.tests.huge")
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(Data(count: SystemPasteboardManager.maximumRepresentationBytes + 1), forType: hugeType))
        XCTAssertTrue(pasteboard.writeObjects([item]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        // A nil snapshot would refuse the paste; an empty one must not.
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(snapshot.items.isEmpty)
        XCTAssertFalse(snapshot.wasEmpty)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))
        XCTAssertEqual(pasteboard.string(forType: .string), "temporary")
    }

    func testOriginallyEmptyClipboardIsRestoredEmpty() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(snapshot.wasEmpty)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restoreTemporarySnapshot(snapshot, sessionID: "session", expectedText: "temporary"))
        XCTAssertNil(pasteboard.string(forType: .string))
        XCTAssertEqual(pasteboard.pasteboardItems?.count ?? 0, 0)
    }

    func testUnreadableRepresentationIsSkippedInsteadOfFailingTheSnapshot() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let lazyType = NSPasteboard.PasteboardType("com.liquidvoice.tests.lazy")
        let provider = EmptyDataProvider()
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setString("still here", forType: .string))
        XCTAssertTrue(item.setDataProvider(provider, forTypes: [lazyType]))
        XCTAssertTrue(pasteboard.writeObjects([item]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot(), "an unreadable type must not block the paste")
        XCTAssertEqual(snapshot.items.first?.representations.map(\.type), [.string])
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))
        XCTAssertEqual(pasteboard.string(forType: .string), "still here")
        withExtendedLifetime(provider) {}
    }

    func testSnapshotRestoresEveryRepresentation() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let customType = NSPasteboard.PasteboardType("com.liquidvoice.tests.custom")
        let customData = Data([0x01, 0x02, 0x03])
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("original", forType: .string))
        XCTAssertTrue(originalItem.setData(customData, forType: customType))
        let secondItem = NSPasteboardItem()
        XCTAssertTrue(secondItem.setString("second", forType: .string))
        XCTAssertTrue(pasteboard.writeObjects([originalItem, secondItem]))
        let originalItems = try XCTUnwrap(pasteboard.pasteboardItems)
        let originalTypes = originalItems.map(\.types)
        let originalRepresentations = originalItems.map { item in
            item.types.map { type in item.data(forType: type) }
        }

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItems = try XCTUnwrap(pasteboard.pasteboardItems)
        XCTAssertEqual(restoredItems.count, 2)
        for (restoredItem, sourceTypes) in zip(restoredItems, originalTypes) {
            XCTAssertEqual(Array(restoredItem.types.prefix(sourceTypes.count)), sourceTypes)
            XCTAssertTrue(restoredItem.types.contains(Self.transientType))
            XCTAssertTrue(restoredItem.types.contains(Self.autoGeneratedType))
            XCTAssertFalse(restoredItem.types.contains(Self.concealedType))
        }
        XCTAssertEqual(
            zip(restoredItems, originalTypes).map { item, types in
                types.map { type in item.data(forType: type) }
            },
            originalRepresentations
        )
        XCTAssertEqual(restoredItems[0].string(forType: .string), "original")
        XCTAssertEqual(restoredItems[0].data(forType: customType), customData)
        XCTAssertEqual(restoredItems[1].string(forType: .string), "second")
    }

    func testSnapshotRestoresImageBeforeTextInOriginalPreferenceOrder() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let imageData = try XCTUnwrap(Self.makeBitmap(width: 2, height: 2).representation(using: .tiff, properties: [:]))
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setData(imageData, forType: .tiff))
        XCTAssertTrue(originalItem.setString("image text fallback", forType: .string))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))
        let originalTypes = try XCTUnwrap(pasteboard.pasteboardItems?.first?.types)
        XCTAssertEqual(originalTypes.first, .tiff)

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.first?.representations.map(\.type), originalTypes)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItem = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertEqual(Array(restoredItem.types.prefix(originalTypes.count)), originalTypes)
        XCTAssertEqual(restoredItem.data(forType: .tiff), imageData)
        XCTAssertEqual(restoredItem.string(forType: .string), "image text fallback")
        XCTAssertNotNil(restoredItem.data(forType: .tiff).flatMap(NSImage.init(data:)))
    }

    func testSnapshotAddsPortableImageBeforeFilenameForICNSOnlyClipboard() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let bitmap = try Self.makeBitmap(width: 2, height: 2)
        bitmap.setColor(NSColor(deviceRed: 0, green: 0, blue: 1, alpha: 1), atX: 0, y: 0)
        let sourceImageData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("Example.icns", forType: .string))
        XCTAssertTrue(originalItem.setData(sourceImageData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertNotNil(snapshot.items.first?.portableImage)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let externalReader = NSPasteboard(name: pasteboard.name)
        let restoredItem = try XCTUnwrap(externalReader.pasteboardItems?.first)
        XCTAssertEqual(restoredItem.types.first, .png)
        XCTAssertEqual(restoredItem.string(forType: .string), "Example.icns")
        XCTAssertEqual(restoredItem.data(forType: icnsType), sourceImageData)
        XCTAssertNotNil(restoredItem.data(forType: .png).flatMap(NSImage.init(data:)))
        XCTAssertTrue(restoredItem.types.contains(Self.transientType))
        XCTAssertTrue(restoredItem.types.contains(Self.autoGeneratedType))
    }

    func testSnapshotAddsPortableImageForImageFileURL() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let temporaryDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("liquidvoice-image-pasteboard-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: temporaryDirectory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: temporaryDirectory) }

        let bitmap = try Self.makeBitmap(width: 1, height: 1)
        bitmap.setColor(NSColor(deviceRed: 1, green: 0, blue: 0, alpha: 1), atX: 0, y: 0)
        let sourceImageData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let imageURL = temporaryDirectory.appendingPathComponent("Example.png")
        try sourceImageData.write(to: imageURL)

        bitmap.setColor(NSColor(deviceRed: 0, green: 0, blue: 1, alpha: 1), atX: 0, y: 0)
        let iconData = try XCTUnwrap(bitmap.representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString(imageURL.absoluteString, forType: .fileURL))
        XCTAssertTrue(originalItem.setString("Example.png", forType: .string))
        XCTAssertTrue(originalItem.setData(iconData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertNotNil(snapshot.items.first?.portableImage)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItem = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertEqual(Array(restoredItem.types.prefix(2)), [.fileURL, .png])
        XCTAssertEqual(restoredItem.string(forType: .fileURL), imageURL.absoluteString)
        XCTAssertEqual(restoredItem.data(forType: icnsType), iconData)
        XCTAssertEqual(restoredItem.data(forType: .png), sourceImageData)
    }

    func testSnapshotUsesEmbeddedImageWhenImageFileURLCannotBeRead() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let iconData = try XCTUnwrap(Self.makeBitmap(width: 1, height: 1).representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("file:///.file/id=123456.789", forType: .fileURL))
        XCTAssertTrue(originalItem.setString("Example.png", forType: .string))
        XCTAssertTrue(originalItem.setData(iconData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertNotNil(snapshot.items.first?.portableImage)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let externalReader = NSPasteboard(name: pasteboard.name)
        let restoredItem = try XCTUnwrap(externalReader.pasteboardItems?.first)
        XCTAssertTrue(restoredItem.types.contains(.png))
        XCTAssertLessThan(
            try XCTUnwrap(restoredItem.types.firstIndex(of: .png)),
            try XCTUnwrap(restoredItem.types.firstIndex(of: .string))
        )
        XCTAssertNotNil(restoredItem.data(forType: .png).flatMap(NSImage.init(data:)))
    }

    func testSnapshotDoesNotTurnNonImageFileIconIntoImage() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }

        let iconData = try XCTUnwrap(Self.makeBitmap(width: 1, height: 1).representation(using: .png, properties: [:]))
        let icnsType = NSPasteboard.PasteboardType("com.apple.icns")
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setString("file:///tmp/Example.txt", forType: .fileURL))
        XCTAssertTrue(originalItem.setString("Example.txt", forType: .string))
        XCTAssertTrue(originalItem.setData(iconData, forType: icnsType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItem = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        XCTAssertFalse(restoredItem.types.contains(.png))
        XCTAssertEqual(restoredItem.string(forType: .fileURL), "file:///tmp/Example.txt")
        XCTAssertEqual(restoredItem.data(forType: icnsType), iconData)
    }

    func testLargeRepresentationUnderTheCapIsSnapshottedAndRestored() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let customType = NSPasteboard.PasteboardType("com.liquidvoice.tests.large")
        let originalData = Data(repeating: 0xab, count: 20 * 1024 * 1024)
        let originalItem = NSPasteboardItem()
        XCTAssertTrue(originalItem.setData(originalData, forType: customType))
        XCTAssertTrue(pasteboard.writeObjects([originalItem]))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.first?.representations.first?.data, originalData)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        XCTAssertEqual(pasteboard.data(forType: customType), originalData)
    }

    func testMoreThanOneHundredItemsAreSnapshottedAndRestored() throws {
        let pasteboard = Self.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let originalItems = (0..<101).map { index in
            let item = NSPasteboardItem()
            item.setString("item \(index)", forType: .string)
            return item
        }
        XCTAssertTrue(pasteboard.writeObjects(originalItems))

        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertEqual(snapshot.items.count, 101)
        XCTAssertTrue(manager.writeTemporaryText("temporary", sessionID: "session"))
        XCTAssertTrue(manager.restore(snapshot))

        let restoredItems = try XCTUnwrap(pasteboard.pasteboardItems)
        XCTAssertEqual(restoredItems.count, 101)
        XCTAssertEqual(restoredItems.first?.string(forType: .string), "item 0")
        XCTAssertEqual(restoredItems.last?.string(forType: .string), "item 100")
    }

    @MainActor
    func testFocusRestoreDoesNotRaiseAllWindowsOfTargetApp() {
        // Issue #748: restoring focus after dictation must NOT raise every window of the
        // target app. `.activateAllWindows` brings forward all windows of the process and
        // destroys a multi-window layout (e.g. WebStorm) on every dictation.
        let options = TypingService.focusRestoreActivationOptions
        XCTAssertTrue(options.contains(.activateIgnoringOtherApps))
        XCTAssertFalse(options.contains(.activateAllWindows))
    }

    // MARK: Helpers

    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    static func makePasteboard() -> NSPasteboard {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name("com.liquidvoice.tests.pasteboard.\(UUID().uuidString)"))
        pasteboard.clearContents()
        return pasteboard
    }

    static func makeBitmap(width: Int, height: Int) throws -> NSBitmapImageRep {
        try XCTUnwrap(
            NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: width,
                pixelsHigh: height,
                bitsPerSample: 8,
                samplesPerPixel: 4,
                hasAlpha: true,
                isPlanar: false,
                colorSpaceName: .deviceRGB,
                bytesPerRow: 0,
                bitsPerPixel: 0
            )
        )
    }
}

/// Declares a type but never provides its data, like an app that quit after copying.
private final class EmptyDataProvider: NSObject, NSPasteboardItemDataProvider {
    func pasteboard(_: NSPasteboard?, item _: NSPasteboardItem, provideDataForType _: NSPasteboard.PasteboardType) {}
}

// MARK: - Ownership

final class PasteboardOwnershipRegressionTests: XCTestCase {
    func testFailureRestorationPreservesNewerCopy() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        pasteboard.setString("original", forType: .string)
        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("dictation", sessionID: "session"))
        pasteboard.clearContents()
        pasteboard.setString("new user copy", forType: .string)
        XCTAssertFalse(manager.restoreTemporarySnapshot(snapshot, sessionID: "session", expectedText: "dictation"))
        XCTAssertEqual(pasteboard.string(forType: .string), "new user copy")
    }

    func testMatchingMarkersDoNotOverrideNewerClipboardGeneration() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        pasteboard.setString("original", forType: .string)
        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("dictation", sessionID: "session"))
        let temporary = try XCTUnwrap(pasteboard.pasteboardItems?.first)
        let copy = NSPasteboardItem()
        for type in temporary.types {
            try copy.setData(XCTUnwrap(temporary.data(forType: type)), forType: type)
        }
        pasteboard.clearContents()
        XCTAssertTrue(pasteboard.writeObjects([copy]))
        XCTAssertFalse(manager.isOwned(sessionID: "session", expectedText: "dictation"))
        XCTAssertFalse(manager.restoreTemporarySnapshot(snapshot, sessionID: "session", expectedText: "dictation"))
        XCTAssertEqual(pasteboard.string(forType: .string), "dictation")
    }

    func testUnchangedTemporaryClipboardCanBeRestored() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        pasteboard.setString("original", forType: .string)
        let manager = SystemPasteboardManager(pasteboard: pasteboard)
        let snapshot = try XCTUnwrap(manager.captureSnapshot())
        XCTAssertTrue(manager.writeTemporaryText("dictation", sessionID: "session"))
        XCTAssertTrue(manager.restoreTemporarySnapshot(snapshot, sessionID: "session", expectedText: "dictation"))
        XCTAssertEqual(pasteboard.string(forType: .string), "original")
    }
}

// MARK: - Invariant 3: the user's clipboard comes back, and back-to-back pastes queue

final class ClipboardPasteSessionTests: XCTestCase {
    private var pasteboard: NSPasteboard!
    private var session: ClipboardPasteSession!

    override func setUp() {
        super.setUp()
        self.pasteboard = TypingServiceTransientPasteboardTests.makePasteboard()
        self.session = ClipboardPasteSession(
            pasteboard: SystemPasteboardManager(pasteboard: self.pasteboard),
            label: "ClipboardPasteSessionTests"
        )
    }

    override func tearDown() {
        self.session.waitUntilIdle()
        self.pasteboard.releaseGlobally()
        super.tearDown()
    }

    func testPasteOffersTheTranscriptThenRestoresTheOriginalClipboard() throws {
        let customType = NSPasteboard.PasteboardType("com.liquidvoice.tests.custom")
        let item = NSPasteboardItem()
        item.setString("before", forType: .string)
        item.setData(Data([7, 8, 9]), forType: customType)
        XCTAssertTrue(self.pasteboard.writeObjects([item]))

        var textAtDispatch: String?
        let failure = self.session.paste(
            "dictated words",
            dispatch: {
                textAtDispatch = self.pasteboard.string(forType: .string)
                return true
            },
            makeConsumptionWait: { {} }
        )
        XCTAssertNil(failure)
        XCTAssertEqual(textAtDispatch, "dictated words")

        self.session.waitUntilIdle()
        XCTAssertEqual(self.pasteboard.string(forType: .string), "before")
        XCTAssertEqual(self.pasteboard.data(forType: customType), Data([7, 8, 9]))
    }

    func testPasteRestoresAnImageClipboard() throws {
        let imageData = try XCTUnwrap(
            TypingServiceTransientPasteboardTests.makeBitmap(width: 3, height: 3).representation(using: .png, properties: [:])
        )
        let item = NSPasteboardItem()
        item.setData(imageData, forType: .png)
        XCTAssertTrue(self.pasteboard.writeObjects([item]))

        XCTAssertNil(self.session.paste("dictated words", dispatch: { true }, makeConsumptionWait: { {} }))
        self.session.waitUntilIdle()

        XCTAssertEqual(self.pasteboard.data(forType: .png), imageData)
        XCTAssertNil(self.pasteboard.string(forType: .string))
    }

    func testRestoreWaitsForTheTargetToConsumeThePaste() {
        self.pasteboard.setString("before", forType: .string)
        let release = DispatchSemaphore(value: 0)

        XCTAssertNil(self.session.paste("dictated words", dispatch: { true }, makeConsumptionWait: { { release.wait() } }))
        XCTAssertEqual(self.pasteboard.string(forType: .string), "dictated words", "restoring early would paste the old clipboard")

        release.signal()
        self.session.waitUntilIdle()
        XCTAssertEqual(self.pasteboard.string(forType: .string), "before")
    }

    func testUserCopyDuringThePasteIsNeverOverwritten() {
        self.pasteboard.setString("before", forType: .string)

        XCTAssertNil(self.session.paste("dictated words", dispatch: { true }, makeConsumptionWait: {
            {
                self.pasteboard.clearContents()
                self.pasteboard.setString("user copy", forType: .string)
            }
        }))
        self.session.waitUntilIdle()

        XCTAssertEqual(self.pasteboard.string(forType: .string), "user copy")
    }

    func testFailedPasteCommandRestoresTheClipboardAtOnce() {
        self.pasteboard.setString("before", forType: .string)

        let failure = self.session.paste("dictated words", dispatch: { false }, makeConsumptionWait: {
            { XCTFail("a paste that was never sent has nothing to wait for") }
        })

        XCTAssertEqual(failure, .pasteCommandFailed)
        XCTAssertEqual(self.pasteboard.string(forType: .string), "before")
    }

    func testBackToBackPastesEachDeliverTheirOwnTextAndRestoreTheOriginal() {
        self.pasteboard.setString("before", forType: .string)
        let texts = (1...5).map { "dictation \($0)" }
        let lock = NSLock()
        var seen: [String: String] = [:]
        let group = DispatchGroup()

        for text in texts {
            group.enter()
            DispatchQueue.global(qos: .userInitiated).async {
                let failure = self.session.paste(
                    text,
                    dispatch: {
                        let onBoard = self.pasteboard.string(forType: .string) ?? ""
                        lock.withLock { seen[text] = onBoard }
                        return true
                    },
                    makeConsumptionWait: { { usleep(20_000) } }
                )
                XCTAssertNil(failure)
                group.leave()
            }
        }

        XCTAssertEqual(group.wait(timeout: .now() + 10), .success)
        self.session.waitUntilIdle()
        XCTAssertEqual(seen, Dictionary(uniqueKeysWithValues: texts.map { ($0, $0) }), "no paste may see another's text")
        XCTAssertEqual(self.pasteboard.string(forType: .string), "before")
    }

    // MARK: Invariant 2: a failed delivery keeps the transcript on the clipboard

    func testKeepTranscriptPutsAnOrdinaryCopyOnTheClipboard() throws {
        self.pasteboard.setString("before", forType: .string)

        let copied = self.expectation(description: "backup written")
        self.session.keepTranscript("kept words") { outcome in
            XCTAssertEqual(outcome, .copied)
            copied.fulfill()
        }
        self.wait(for: [copied], timeout: 5)

        let item = try XCTUnwrap(self.pasteboard.pasteboardItems?.first)
        XCTAssertEqual(item.string(forType: .string), "kept words")
        XCTAssertFalse(item.types.contains(TypingServiceTransientPasteboardTests.transientType), "the backup is for the user, not hidden")
        XCTAssertFalse(item.types.contains(TypingServiceTransientPasteboardTests.concealedType))
    }

    func testKeepTranscriptWaitsForAPendingRestoreAndWins() {
        self.pasteboard.setString("before", forType: .string)
        let release = DispatchSemaphore(value: 0)
        XCTAssertNil(self.session.paste("first dictation", dispatch: { true }, makeConsumptionWait: { { release.wait() } }))

        let copied = self.expectation(description: "backup written")
        self.session.keepTranscript("second dictation") { outcome in
            XCTAssertEqual(outcome, .copied)
            copied.fulfill()
        }
        release.signal()
        self.wait(for: [copied], timeout: 5)
        self.session.waitUntilIdle()

        XCTAssertEqual(self.pasteboard.string(forType: .string), "second dictation")
    }

    func testKeepTranscriptNeverClobbersANewerUserCopy() {
        self.pasteboard.setString("before", forType: .string)
        let release = DispatchSemaphore(value: 0)
        XCTAssertNil(self.session.paste("first dictation", dispatch: { true }, makeConsumptionWait: {
            {
                release.wait()
                self.pasteboard.clearContents()
                self.pasteboard.setString("user copy", forType: .string)
            }
        }))

        let finished = self.expectation(description: "backup decided")
        self.session.keepTranscript("failed dictation") { outcome in
            XCTAssertEqual(outcome, .newerClipboardCopy)
            finished.fulfill()
        }
        release.signal()
        self.wait(for: [finished], timeout: 5)

        XCTAssertEqual(self.pasteboard.string(forType: .string), "user copy")
    }

    func testTheConsumptionWaitIsBuiltAfterEarlierPastesAndWithTheTranscriptOnTheBoard() {
        self.pasteboard.setString("before", forType: .string)
        let release = DispatchSemaphore(value: 0)
        XCTAssertNil(self.session.paste("first", dispatch: { true }, makeConsumptionWait: { { release.wait() } }))

        let secondDone = self.expectation(description: "second paste dispatched")
        var boardWhenBuilt: String?
        DispatchQueue.global().async {
            XCTAssertNil(self.session.paste("second", dispatch: { true }, makeConsumptionWait: {
                boardWhenBuilt = self.pasteboard.string(forType: .string)
                return {}
            }))
            secondDone.fulfill()
        }
        usleep(50_000)
        XCTAssertNil(boardWhenBuilt, "the second paste must wait for the first to finish")
        release.signal()
        self.wait(for: [secondDone], timeout: 5)
        XCTAssertEqual(boardWhenBuilt, "second")
    }

    func testAReadBackMissNeverReplacesACopyMadeAfterThePaste() {
        self.pasteboard.setString("before", forType: .string)
        XCTAssertNil(self.session.paste("dictated", dispatch: { true }, makeConsumptionWait: { {} }))
        let revisionAtPaste = self.session.changeCount
        self.session.waitUntilIdle()
        // The user copies something while the read-back is still deciding.
        self.pasteboard.clearContents()
        self.pasteboard.setString("user copy", forType: .string)

        let decided = self.expectation(description: "backup decided")
        self.session.keepTranscript("dictated", since: revisionAtPaste) { outcome in
            XCTAssertEqual(outcome, .newerClipboardCopy)
            decided.fulfill()
        }
        self.wait(for: [decided], timeout: 5)
        XCTAssertEqual(self.pasteboard.string(forType: .string), "user copy")
    }

    func testAReadBackMissReplacesOnlyTheRestoredClipboard() {
        self.pasteboard.setString("before", forType: .string)
        XCTAssertNil(self.session.paste("dictated", dispatch: { true }, makeConsumptionWait: { {} }))
        let revisionAtPaste = self.session.changeCount
        self.session.waitUntilIdle()
        XCTAssertEqual(self.pasteboard.string(forType: .string), "before")

        let decided = self.expectation(description: "backup decided")
        self.session.keepTranscript("dictated", since: revisionAtPaste) { outcome in
            XCTAssertEqual(outcome, .copied)
            decided.fulfill()
        }
        self.wait(for: [decided], timeout: 5)
        XCTAssertEqual(self.pasteboard.string(forType: .string), "dictated")
    }

    func testABackupNeverReplacesAUserCopyThatAnotherPasteRestored() {
        self.pasteboard.setString("before", forType: .string)
        let revisionAtFailure = self.session.changeCount
        // After the failure the user copies something, then a queued dictation pastes and
        // restores that copy. The restore is ours, but what it put back is the user's.
        self.pasteboard.clearContents()
        self.pasteboard.setString("user copy", forType: .string)
        XCTAssertNil(self.session.paste("next dictation", dispatch: { true }, makeConsumptionWait: { {} }))
        self.session.waitUntilIdle()
        XCTAssertEqual(self.pasteboard.string(forType: .string), "user copy")

        let decided = self.expectation(description: "backup decided")
        self.session.keepTranscript("failed dictation", since: revisionAtFailure) { outcome in
            XCTAssertEqual(outcome, .newerClipboardCopy)
            decided.fulfill()
        }
        self.wait(for: [decided], timeout: 5)
        XCTAssertEqual(self.pasteboard.string(forType: .string), "user copy")
    }

    func testTheSameTranscriptIsNotCopiedTwice() {
        self.pasteboard.setString("before", forType: .string)
        let first = self.expectation(description: "first backup")
        self.session.keepTranscript("kept words") { _ in first.fulfill() }
        self.wait(for: [first], timeout: 5)
        let afterFirst = self.session.changeCount

        let second = self.expectation(description: "second backup")
        self.session.keepTranscript("kept words") { outcome in
            XCTAssertEqual(outcome, .alreadyOnClipboard)
            second.fulfill()
        }
        self.wait(for: [second], timeout: 5)
        XCTAssertEqual(self.session.changeCount, afterFirst, "a second identical copy would show twice in clipboard history")
    }

    func testAnEmptyTranscriptIsReportedAsSuch() {
        let decided = self.expectation(description: "backup decided")
        self.session.keepTranscript("") { outcome in
            XCTAssertEqual(outcome, .emptyText)
            decided.fulfill()
        }
        self.wait(for: [decided], timeout: 5)
    }

    func testWhenNothingCouldBeSnapshottedTheTranscriptIsLeftAsAVisibleCopy() throws {
        let hugeType = NSPasteboard.PasteboardType("com.liquidvoice.tests.huge")
        let item = NSPasteboardItem()
        XCTAssertTrue(item.setData(Data(count: SystemPasteboardManager.maximumRepresentationBytes + 1), forType: hugeType))
        XCTAssertTrue(self.pasteboard.writeObjects([item]))

        XCTAssertNil(self.session.paste("dictated words", dispatch: { true }, makeConsumptionWait: { {} }))
        self.session.waitUntilIdle()

        let leftover = try XCTUnwrap(self.pasteboard.pasteboardItems?.first)
        XCTAssertEqual(leftover.string(forType: .string), "dictated words")
        XCTAssertFalse(leftover.types.contains(TypingServiceTransientPasteboardTests.transientType), "must not stay hidden from clipboard history")
        XCTAssertFalse(leftover.types.contains(TypingServiceTransientPasteboardTests.concealedType))
    }
}

// MARK: - Invariant 5: the synthesized Cmd+V never leaves Command held

final class PasteCommandEventTests: XCTestCase {
    func testGlobalPasteSequencePressesAndReleasesCommandExplicitly() {
        let events = PasteCommandEvents.makeGlobalPasteEvents(pasteKeyCode: 9)
        XCTAssertEqual(events.count, 4)
        let keyCodes = events.map { CGKeyCode($0.getIntegerValueField(.keyboardEventKeycode)) }
        XCTAssertEqual(keyCodes, [CGKeyCode(kVK_Command), 9, 9, CGKeyCode(kVK_Command)])
        // Modifier presses are flagsChanged events, exactly like a physical Command key.
        XCTAssertEqual(events.map(\.type), [.flagsChanged, .keyDown, .keyUp, .flagsChanged])
        XCTAssertTrue(events[0].flags.contains(.maskCommand))
        XCTAssertTrue(events[1].flags.contains(.maskCommand))
        XCTAssertTrue(events[2].flags.contains(.maskCommand))
        XCTAssertFalse(events[3].flags.contains(.maskCommand), "the final event must release Command")
    }

    func testGlobalPasteUsesTheLayoutKeyForV() {
        let events = PasteCommandEvents.makeGlobalPasteEvents(pasteKeyCode: 47)
        XCTAssertEqual(events.map { CGKeyCode($0.getIntegerValueField(.keyboardEventKeycode)) }[1...2], [47, 47])
    }

    func testTargetedPastePairCarriesCommandOnlyOnTheVKey() {
        let events = PasteCommandEvents.makeTargetedPasteEvents(pasteKeyCode: 9)
        XCTAssertEqual(events.count, 2)
        XCTAssertEqual(events.map(\.type), [.keyDown, .keyUp])
        XCTAssertEqual(events.map { CGKeyCode($0.getIntegerValueField(.keyboardEventKeycode)) }, [9, 9])
        XCTAssertTrue(events.allSatisfy { $0.flags.contains(.maskCommand) })
    }

    func testEverySynthesizedPasteEventIsTaggedForTheHotkeyTap() throws {
        for event in PasteCommandEvents.makeGlobalPasteEvents(pasteKeyCode: 9) + PasteCommandEvents.makeTargetedPasteEvents(pasteKeyCode: 9) {
            XCTAssertTrue(PasteCommandEvents.isSynthesized(event))
        }
        let physical = try XCTUnwrap(CGEvent(keyboardEventSource: nil, virtualKey: 9, keyDown: true))
        XCTAssertFalse(PasteCommandEvents.isSynthesized(physical))
    }
}

// MARK: - Keyboard layouts (ported from upstream's standalone resolver/cache tests)

final class PasteKeyCodeTests: XCTestCase {
    func testResolverFindsCommandVAcrossInstalledLayouts() throws {
        // Reads installed layout data without enabling or switching any user input source.
        let sources = try XCTUnwrap(TISCreateInputSourceList(nil, true).takeRetainedValue() as? [TISInputSource])
        var checked = 0
        for (identifier, expected): (String, CGKeyCode) in [
            ("com.apple.keylayout.US", 9),
            ("com.apple.keylayout.Dvorak", 47),
            ("com.apple.keylayout.DVORAK-QWERTYCMD", 9),
            ("com.apple.keylayout.French", 9),
            ("com.apple.keylayout.Russian", 9),
        ] {
            guard let source = sources.first(where: { source in
                guard let pointer = TISGetInputSourceProperty(source, kTISPropertyInputSourceID) else { return false }
                return Unmanaged<CFString>.fromOpaque(pointer).takeUnretainedValue() as String == identifier
            }), let pointer = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
                continue
            }
            let data = Unmanaged<CFData>.fromOpaque(pointer).takeUnretainedValue() as Data
            XCTAssertEqual(PasteKeyCodeResolver.resolve(layoutData: data, keyboardType: UInt32(LMGetKbdType())), expected, identifier)
            checked += 1
        }
        try XCTSkipIf(checked == 0, "no reference keyboard layouts installed")
    }

    func testResolverFallsBackToQWERTYWhenTheLayoutIsUnavailable() {
        XCTAssertEqual(PasteKeyCodeResolver.resolve(layoutData: nil, keyboardType: 0), 9)
        XCTAssertEqual(PasteKeyCodeResolver.resolve(layoutData: Data(), keyboardType: 0), 9)
    }

    @MainActor
    func testCacheResolvesOnceThenOnlyOnLayoutChanges() {
        let name = Notification.Name("LiquidVoice.PasteKeyCacheTest.\(UUID().uuidString)")
        var selectedKey: CGKeyCode = 9
        var lookups = 0
        let cache = PasteKeyCodeCache(notificationName: name) {
            lookups += 1
            return selectedKey
        }
        cache.start()
        cache.start()
        XCTAssertEqual(lookups, 1, "startup must resolve exactly once")
        for _ in 0..<1000 {
            XCTAssertEqual(cache.snapshot(), 9)
        }
        XCTAssertEqual(lookups, 1, "pastes must not query the layout")

        selectedKey = 47
        DistributedNotificationCenter.default().postNotificationName(name, object: nil, userInfo: nil, deliverImmediately: true)
        let deadline = Date().addingTimeInterval(2)
        while cache.snapshot() != 47, Date() < deadline {
            RunLoop.current.run(until: Date().addingTimeInterval(0.005))
        }
        XCTAssertEqual(cache.snapshot(), 47, "a layout-change notification must update the snapshot")
    }

    @MainActor
    func testCachedReadsNeverWaitOnTheMainThread() {
        let cache = PasteKeyCodeCache(notificationName: Notification.Name("LiquidVoice.PasteKeyCacheTest.\(UUID().uuidString)")) { 9 }
        cache.start()
        let finished = DispatchSemaphore(value: 0)
        DispatchQueue.global().async {
            DispatchQueue.concurrentPerform(iterations: 10000) { _ in
                _ = cache.snapshot()
            }
            finished.signal()
        }
        // The main thread is blocked here on purpose.
        XCTAssertEqual(finished.wait(timeout: .now() + 2), .success)
    }
}

// MARK: - Refusing a target that cannot take text, and the paste read-back

final class DeliveryTargetAssessmentTests: XCTestCase {
    func testTextRolesAreEditable() {
        for role in ["AXTextField", "AXTextArea", "AXComboBox", "AXSecureTextField"] {
            XCTAssertEqual(DeliveryTargetAssessment.classify(role: role, valueSettable: false), .editable(role: role))
        }
    }

    func testSettableValueWinsOverRole() {
        XCTAssertEqual(DeliveryTargetAssessment.classify(role: "AXStaticText", valueSettable: true), .editable(role: "AXStaticText"))
    }

    func testControlsAndStaticContentAreRefused() {
        for role in ["AXButton", "AXStaticText", "AXImage", "AXMenuItem", "AXSlider", "AXCheckBox", "AXLink"] {
            XCTAssertTrue(DeliveryTargetAssessment.classify(role: role, valueSettable: false).isCertainlyNotEditable, role)
        }
    }

    func testContainersStayUnknownSoPasteProceeds() {
        // Apps that draw their own UI (GPU terminals such as c11 and Ghostty, remote desktops)
        // report the window or application as the focused element and still accept Cmd+V.
        for role in ["AXWindow", "AXSheet", "AXDrawer", "AXApplication", "AXGroup", "AXWebArea", "AXCell", "AXUnknown"] {
            XCTAssertEqual(DeliveryTargetAssessment.classify(role: role, valueSettable: false), .unknown(reason: "role_\(role)"), role)
        }
    }
}

final class PasteVerifierTests: XCTestCase {
    private func snapshot(value: String?, count: Int?, caret: CFRange?) -> PasteVerifier.Snapshot {
        PasteVerifier.Snapshot(
            element: AXUIElementCreateSystemWide(),
            pid: 1,
            role: "AXTextArea",
            value: value,
            characterCount: count,
            caret: caret
        )
    }

    func testNotLandedVerdictWaitsAtLeastOneAndAHalfSeconds() {
        // A slow app that applies Cmd+V late must never draw a failure card.
        XCTAssertGreaterThanOrEqual(PasteVerifier.totalDecisionDelay, 1.5)
        XCTAssertEqual(PasteVerifier.finalCheckDelay, 1.0)
    }

    func testReadBackStandsDownWhenUserActsAfterPaste() {
        // Return pressed 0.4 s after the paste; the verdict arrives at 1.5 s.
        XCTAssertTrue(PasteVerifier.userActedAfterPaste(secondsSinceLastInput: 1.1, secondsSincePaste: 1.5))
        // Our own synthesized V at the paste instant is not user input.
        XCTAssertFalse(PasteVerifier.userActedAfterPaste(secondsSinceLastInput: 1.48, secondsSincePaste: 1.5))
        // Nothing typed since well before the paste.
        XCTAssertFalse(PasteVerifier.userActedAfterPaste(secondsSinceLastInput: 30, secondsSincePaste: 1.5))
    }

    func testTextAppearingInTheValueConfirmsTheLanding() {
        let before = self.snapshot(value: "Hello", count: 5, caret: CFRange(location: 5, length: 0))
        let after = self.snapshot(value: "Hello world", count: 11, caret: CFRange(location: 11, length: 0))
        XCTAssertEqual(PasteVerifier.confirmation(before: before, after: after, needle: "world"), .confirmed(method: "value"))
    }

    func testCountAdvanceConfirmsWhenTheValueIsUnreadable() {
        let before = self.snapshot(value: nil, count: 10, caret: nil)
        let after = self.snapshot(value: nil, count: 15, caret: nil)
        XCTAssertEqual(PasteVerifier.confirmation(before: before, after: after, needle: "hello"), .confirmed(method: "count"))
    }

    func testUnchangedFieldIsTheOnlyNotLandedCase() {
        let before = self.snapshot(value: "draft", count: 5, caret: CFRange(location: 5, length: 0))
        XCTAssertNil(PasteVerifier.unchangedVerdict(before: before, after: before), "fully unchanged → caller reports notLanded")
        let changed = self.snapshot(value: "draft!", count: 6, caret: CFRange(location: 6, length: 0))
        XCTAssertEqual(PasteVerifier.unchangedVerdict(before: before, after: changed), .unknown(reason: "changed_without_text"))
        let blind = self.snapshot(value: nil, count: 5, caret: CFRange(location: 5, length: 0))
        XCTAssertEqual(
            PasteVerifier.unchangedVerdict(before: blind, after: blind),
            .unknown(reason: "signals_incomplete value=false count=true caret=true")
        )
    }
}

// MARK: - Destination chosen at stop

final class DictationTargetPolicyTests: XCTestCase {
    private let ownPID: pid_t = 999

    private func target(_ pid: pid_t) -> DictationTarget {
        DictationTarget(pid: pid, bundleIdentifier: "test.app.\(pid)", window: nil, element: nil)
    }

    func testFollowsTheCursorAtStopByDefault() {
        let result = DictationTargetPolicy.selectStopTarget(
            current: self.target(200), original: self.target(100), returnToStartingField: false, ownPID: self.ownPID
        )
        XCTAssertEqual(result?.pid, 200)
    }

    func testReturnToStartingFieldSendsItBack() {
        let result = DictationTargetPolicy.selectStopTarget(
            current: self.target(200), original: self.target(100), returnToStartingField: true, ownPID: self.ownPID
        )
        XCTAssertEqual(result?.pid, 100)
    }

    func testOwnOverlayFocusRecoversTheStartingTarget() {
        let result = DictationTargetPolicy.selectStopTarget(
            current: self.target(self.ownPID), original: self.target(100), returnToStartingField: false, ownPID: self.ownPID
        )
        XCTAssertEqual(result?.pid, 100)
    }

    func testUnreadableFocusAtStopFallsBackToTheStartingTarget() {
        XCTAssertEqual(
            DictationTargetPolicy.selectStopTarget(current: nil, original: self.target(100), returnToStartingField: false, ownPID: self.ownPID)?.pid,
            100
        )
        XCTAssertNil(DictationTargetPolicy.selectStopTarget(current: nil, original: nil, returnToStartingField: true, ownPID: self.ownPID))
    }

    func testLiquidVoicesOwnMainWindowIsARealDestination() {
        let result = DictationTargetPolicy.selectStopTarget(
            current: self.target(self.ownPID), original: self.target(100), returnToStartingField: false,
            ownPID: self.ownPID, ownFocusIsOverlay: false
        )
        XCTAssertEqual(result?.pid, self.ownPID)
    }

    func testDeliveryIsReadyExactlyWhenTheTargetAppIsInFront() {
        // Not in front after recovery (c11 left behind a Cmd-Tab, say): refuse, so the card
        // shows and the transcript stays on the clipboard instead of a blind paste.
        for broughtBack in [false, true] {
            for fieldConfirmed in [false, true] {
                XCTAssertEqual(
                    TypingService.preparationVerdict(appInFront: false, broughtBack: broughtBack, fieldConfirmed: fieldConfirmed),
                    .failed
                )
            }
        }
        // In front: always ready, whether or not the exact field could be confirmed (Word,
        // Excel, Zed, Warp and kitty recreate or misreport their focused element).
        XCTAssertEqual(TypingService.preparationVerdict(appInFront: true, broughtBack: false, fieldConfirmed: true), .alreadyFocused)
        XCTAssertEqual(TypingService.preparationVerdict(appInFront: true, broughtBack: false, fieldConfirmed: false), .appInFrontFieldUnconfirmed)
        XCTAssertEqual(TypingService.preparationVerdict(appInFront: true, broughtBack: true, fieldConfirmed: true), .restoredExactTarget)
        XCTAssertEqual(TypingService.preparationVerdict(appInFront: true, broughtBack: true, fieldConfirmed: false), .activatedForRecovery)
        XCTAssertTrue(TypingService.FocusPreparationResult.appInFrontFieldUnconfirmed.isReady)
    }

    func testReturnToStartingFieldWithoutAStartTargetUsesTheCursor() {
        let result = DictationTargetPolicy.selectStopTarget(
            current: self.target(200), original: nil, returnToStartingField: true, ownPID: self.ownPID
        )
        XCTAssertEqual(result?.pid, 200)
    }
}

// MARK: - Invariant 2: failures are shown and the transcript is kept

@MainActor
final class DeliveryFailureReportingTests: XCTestCase {
    private var pasteboard: NSPasteboard!
    private var session: ClipboardPasteSession!
    private var originalHandler: ((DeliveryFailureReport) -> Void)!
    private var reported: [DeliveryFailureReport] = []

    override func setUp() async throws {
        try await super.setUp()
        self.pasteboard = TypingServiceTransientPasteboardTests.makePasteboard()
        self.pasteboard.setString("before", forType: .string)
        self.session = ClipboardPasteSession(pasteboard: SystemPasteboardManager(pasteboard: self.pasteboard), label: "DeliveryFailureReportingTests")
        self.originalHandler = TypingService.deliveryFailureHandler
        TypingService.deliveryFailureHandler = { [weak self] report in
            self?.reported.append(report)
        }
    }

    override func tearDown() async throws {
        TypingService.deliveryFailureHandler = self.originalHandler
        self.session.waitUntilIdle()
        self.pasteboard.releaseGlobally()
        try await super.tearDown()
    }

    func testEveryFailureExceptAnEmptyTranscriptIsShown() {
        for failure in TextDeliveryFailure.allCases {
            XCTAssertEqual(failure.isUserVisible, failure != .emptyText, failure.rawValue)
        }
        XCTAssertEqual(TextDeliveryFailure.noEditableTarget.userFacingTitle, "No text field focused")
        XCTAssertEqual(TextDeliveryFailure.pasteNotLanded.userFacingTitle, "Text wasn't inserted")
        XCTAssertEqual(TextDeliveryFailure.accessibilityNotTrusted.userFacingTitle, "Enable Accessibility to insert text")
    }

    func testAReportedFailureShowsTheCardAndKeepsTheTranscriptOnTheClipboard() async {
        TypingService.reportDeliveryFailure(.noEditableTarget, transcript: "lost words", inHistory: true, pasteSession: self.session)
        await self.waitForReports(1)
        self.session.waitUntilIdle()

        XCTAssertEqual(
            self.reported.first,
            DeliveryFailureReport(failure: .noEditableTarget, transcript: "lost words", clipboard: .copied, inHistory: true)
        )
        XCTAssertEqual(self.pasteboard.string(forType: .string), "lost words")
    }

    func testTheCardSaysSoWhenANewerCopyKeptTheTranscriptOffTheClipboard() async {
        let revisionAtFailure = self.session.changeCount
        self.pasteboard.clearContents()
        self.pasteboard.setString("user copy", forType: .string)

        TypingService.reportDeliveryFailure(.pasteNotLanded, transcript: "lost words", inHistory: false, since: revisionAtFailure, pasteSession: self.session)
        await self.waitForReports(1)

        XCTAssertEqual(self.reported.first?.clipboard, .newerClipboardCopy)
        XCTAssertEqual(self.reported.first?.inHistory, false)
        XCTAssertEqual(self.pasteboard.string(forType: .string), "user copy")
    }

    func testTheCardLineMatchesWhereTheTranscriptActuallyIs() {
        let line = DeliveryFailureOverlayController.detailText
        XCTAssertEqual(line(.copied, true), "Kept on your clipboard and in history.")
        XCTAssertEqual(line(.alreadyOnClipboard, false), "Kept on your clipboard.")
        XCTAssertEqual(line(.newerClipboardCopy, true), "In history. Your newer clipboard was left alone.")
        XCTAssertEqual(line(.newerClipboardCopy, false), "Your newer clipboard was left alone. Use Copy.")
        XCTAssertEqual(line(.writeFailed, true), "In history. The clipboard couldn't be written.")
        XCTAssertEqual(line(.writeFailed, false), "The clipboard couldn't be written. Use Copy.")
        // Never claims history for text that is not in it (rewrite output, debug deliveries).
        for outcome in [TranscriptBackupOutcome.copied, .alreadyOnClipboard, .newerClipboardCopy, .writeFailed] {
            XCTAssertFalse(line(outcome, false).contains("history"), outcome.rawValue)
        }
    }

    func testAnEmptyTranscriptIsNeitherShownNorCopied() async {
        TypingService.reportDeliveryFailure(.emptyText, transcript: "", inHistory: false, pasteSession: self.session)
        try? await Task.sleep(nanoseconds: 100_000_000)
        self.session.waitUntilIdle()

        XCTAssertTrue(self.reported.isEmpty)
        XCTAssertEqual(self.pasteboard.string(forType: .string), "before")
    }

    func testWithoutAccessibilityTheDictationIsKeptAndTheUserIsTold() async throws {
        try XCTSkipIf(AXIsProcessTrusted(), "with Accessibility granted this would type into the focused app")
        let typing = TypingService(pasteSession: self.session)
        var result: TextDeliveryResult?

        typing.typeOutputPlanInstantly(.plain("dictated words"), preferredTargetPID: nil, textReadyAt: nil) { result = $0 }
        await self.waitForReports(1)
        self.session.waitUntilIdle()

        XCTAssertEqual(result, .recoverableFailure(.accessibilityNotTrusted))
        XCTAssertEqual(self.reported.first?.failure, .accessibilityNotTrusted)
        XCTAssertEqual(self.reported.first?.clipboard, .copied)
        XCTAssertEqual(self.reported.first?.inHistory, false, "a bare TypingService call does not claim history")
        XCTAssertEqual(self.pasteboard.string(forType: .string), "dictated words")
    }

    private func waitForReports(_ count: Int) async {
        let deadline = Date().addingTimeInterval(3)
        while self.reported.count < count, Date() < deadline {
            try? await Task.sleep(nanoseconds: 10_000_000)
        }
    }
}

// MARK: - Settings (defaults follow upstream: both off)

@MainActor
final class DeliverySettingsTests: XCTestCase {
    func testPasteCheckIsOffByDefault() {
        let original = UserDefaults.standard.object(forKey: "ShowPasteCheckAlerts")
        defer { UserDefaults.standard.set(original, forKey: "ShowPasteCheckAlerts") }
        UserDefaults.standard.removeObject(forKey: "ShowPasteCheckAlerts")
        XCTAssertFalse(SettingsStore.shared.showPasteCheckAlerts)
    }

    func testReturnToStartingFieldIsOffByDefault() {
        let original = UserDefaults.standard.object(forKey: "ReturnDictationToStartingField")
        defer { UserDefaults.standard.set(original, forKey: "ReturnDictationToStartingField") }
        UserDefaults.standard.removeObject(forKey: "ReturnDictationToStartingField")
        XCTAssertFalse(SettingsStore.shared.returnDictationToStartingField)
    }

    func testBothSettingsRestoreFromABackupAndOlderBackupsLeaveThemAlone() async throws {
        let settings = SettingsStore.shared
        let keys = ["ShowPasteCheckAlerts", "ReturnDictationToStartingField"]
        let originals = keys.map { UserDefaults.standard.object(forKey: $0) }
        defer {
            for (key, value) in zip(keys, originals) {
                UserDefaults.standard.set(value, forKey: key)
            }
        }

        settings.showPasteCheckAlerts = true
        settings.returnDictationToStartingField = true
        let encoded = try await BackupService.shared.encode(BackupService.shared.makeBackupDocument())

        // Restore from the backup: both come back on.
        settings.showPasteCheckAlerts = false
        settings.returnDictationToStartingField = false
        settings.restore(from: try BackupService.shared.decode(encoded).settings)
        XCTAssertTrue(settings.showPasteCheckAlerts)
        XCTAssertTrue(settings.returnDictationToStartingField)

        // A backup made before these settings existed leaves the current values alone.
        var root = try XCTUnwrap(JSONSerialization.jsonObject(with: encoded) as? [String: Any])
        var encodedSettings = try XCTUnwrap(root["settings"] as? [String: Any])
        encodedSettings.removeValue(forKey: "showPasteCheckAlerts")
        encodedSettings.removeValue(forKey: "returnDictationToStartingField")
        root["settings"] = encodedSettings
        let legacy = try BackupService.shared.decode(JSONSerialization.data(withJSONObject: root))
        XCTAssertNil(legacy.settings.showPasteCheckAlerts)
        settings.showPasteCheckAlerts = false
        settings.returnDictationToStartingField = false
        settings.restore(from: legacy.settings)
        XCTAssertFalse(settings.showPasteCheckAlerts)
        XCTAssertFalse(settings.returnDictationToStartingField)
    }
}

// MARK: - Invariant 1: c11 and Ghostty always get the clipboard paste

final class TerminalRoutingTests: XCTestCase {
    @MainActor
    func testTerminalsAlwaysPasteAreNeverRefusedNeverTypeAndNeverReadBack() {
        for mode in SettingsStore.TextInsertionMode.allCases {
            for pasteCheck in [false, true] {
                for sendKeyFollows in [false, true] {
                    let route = TypingService.DeliveryRoute.decide(
                        isTerminal: true, mode: mode, pasteCheckEnabled: pasteCheck, sendKeyFollows: sendKeyFollows
                    )
                    let label = "mode=\(mode.rawValue) pasteCheck=\(pasteCheck) sendKey=\(sendKeyFollows)"
                    XCTAssertTrue(route.pastesFirst, label)
                    XCTAssertFalse(route.refusesNonEditableFocus, label)
                    XCTAssertFalse(route.fallsBackToDirectTyping, label)
                    XCTAssertFalse(route.readsPasteBack, label)
                }
            }
        }
    }

    @MainActor
    func testOtherAppsFollowTheInsertionModeAndThePasteCheck() {
        let standard = TypingService.DeliveryRoute.decide(isTerminal: false, mode: .standard, pasteCheckEnabled: false, sendKeyFollows: false)
        XCTAssertEqual(
            standard,
            .init(refusesNonEditableFocus: true, pastesFirst: false, fallsBackToDirectTyping: true, readsPasteBack: false)
        )
        let reliable = TypingService.DeliveryRoute.decide(isTerminal: false, mode: .reliablePaste, pasteCheckEnabled: true, sendKeyFollows: false)
        XCTAssertEqual(
            reliable,
            .init(refusesNonEditableFocus: true, pastesFirst: true, fallsBackToDirectTyping: true, readsPasteBack: true)
        )
        // A send key right after the paste empties the field; the read-back would misreport.
        let sending = TypingService.DeliveryRoute.decide(isTerminal: false, mode: .reliablePaste, pasteCheckEnabled: true, sendKeyFollows: true)
        XCTAssertFalse(sending.readsPasteBack)
    }

    @MainActor
    func testC11AndGhosttyAreForcedOntoClipboardPaste() {
        // c11 and Ghostty silently dropped direct CGEvent text; they must stay on Reliable Paste.
        XCTAssertTrue(TypingService.isGhosttyFamily(bundleIdentifier: "com.stage11.c11"))
        XCTAssertTrue(TypingService.isGhosttyFamily(bundleIdentifier: "com.mitchellh.ghostty"))
        XCTAssertFalse(TypingService.isGhosttyFamily(bundleIdentifier: "com.apple.TextEdit"))
        XCTAssertFalse(TypingService.isGhosttyFamily(bundleIdentifier: nil))
    }
}
