import AppKit
import Carbon.HIToolbox
import Foundation
import UniformTypeIdentifiers

// Clipboard snapshot and restore ported from altic-dev/FluidVoice by grohith327 and altic-dev:
//   @b0d64436 Migrate to clipboard paste (ordered snapshot, session-owned temporary write)
//   @b1184755 / @03477453 restore image clipboard, fix restoring image snapshot
//   @4cb6683f keep an image file's encoded bytes instead of re-encoding it
//   @a2d6ef32 conceal temporary dictation entries
//   @bbaedd94 cap snapshot representations at 32 MB
//   @a3c896a7 preserve filenames when oversized payloads are skipped
//   @7d6d0e7c keep a transcript backup without clobbering a newer copy
//   @ebbff23a / @c0118882 tag the synthetic Cmd+V and release Command after it
//
// What differs from upstream, on purpose:
//   - No @MainActor coordinator. Liquid Voice keeps its serial typing worker (dictations queue,
//     never drop), so one session at a time owns the pasteboard from snapshot to restore,
//     serialized by a semaphore, and restore timing stays per target (terminals 1 s, other
//     apps until the paste is seen in the field or 5 s).
//   - A representation whose data cannot be read is skipped instead of failing the whole
//     snapshot. A failed snapshot would push c11/Ghostty back onto direct typing, the path
//     that silently dropped text there.
//   - An originally empty clipboard is restored to empty.
//   - Clipboard audit tracing (@daa0f2d3, @208566c2) is not ported.

nonisolated struct PasteboardSnapshot: Equatable, @unchecked Sendable {
    struct Item: Equatable {
        struct Representation: Equatable {
            let type: NSPasteboard.PasteboardType
            let data: Data
        }

        /// AppKit uses source order as representation preference, so this must remain ordered.
        let representations: [Representation]
        /// Materialized while the original owner still provides file access or promised image data.
        let portableImage: Representation?

        init(representations: [Representation], portableImage: Representation? = nil) {
            self.representations = representations
            self.portableImage = portableImage
        }
    }

    let items: [Item]
    /// The clipboard held nothing at all. Restoring then means clearing it again.
    let wasEmpty: Bool

    init(items: [Item], wasEmpty: Bool = false) {
        self.items = items
        self.wasEmpty = wasEmpty
    }
}

/// Pasteboard access used by a paste session. Callers serialize access (see
/// `ClipboardPasteSession`); implementations are not thread-safe on their own.
nonisolated protocol PasteboardManaging: AnyObject {
    var changeCount: Int { get }
    func captureSnapshot() -> PasteboardSnapshot?
    func writeTemporaryText(_ text: String, sessionID: String) -> Bool
    func writeIntentionalText(_ text: String) -> Bool
    func isOwned(sessionID: String, expectedText: String) -> Bool
    func restore(_ snapshot: PasteboardSnapshot) -> Bool
    func restoreTemporarySnapshot(_ snapshot: PasteboardSnapshot, sessionID: String, expectedText: String) -> Bool
    /// Whether `changeCount` is a clipboard revision this manager produced (a temporary write,
    /// a restore or an intentional copy), as opposed to one the user or another app made.
    func producedRevision(_ changeCount: Int) -> Bool
    /// Whether the clipboard already holds exactly `text` as an ordinary, visible copy.
    func holdsIntentionalText(_ text: String) -> Bool
}

nonisolated final class SystemPasteboardManager: PasteboardManaging, @unchecked Sendable {
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    static let sessionType = NSPasteboard.PasteboardType(
        "\(Bundle.main.bundleIdentifier ?? "com.FluidApp.app").PasteSession"
    )
    private static let fileSemanticTypes: Set<NSPasteboard.PasteboardType> = [
        .fileURL,
        NSPasteboard.PasteboardType("NSFilenamesPboardType"),
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-url"),
        NSPasteboard.PasteboardType("com.apple.pasteboard.promised-file-content-type"),
        NSPasteboard.PasteboardType("com.apple.filepromise"),
    ]

    /// A representation larger than this is left out of the snapshot: the paste must never
    /// wait on copying it, and the small ones (strings, file URLs) still restore. A missing
    /// snapshot would block the paste, so an oversized clipboard yields a smaller snapshot
    /// rather than none.
    static let maximumRepresentationBytes = 32 * 1024 * 1024
    /// Decoding and re-encoding an image to PNG costs time proportional to its pixels; skip
    /// it for large sources and keep their original bytes only.
    static let maximumPortableImageSourceBytes = 16 * 1024 * 1024

    private let pasteboard: NSPasteboard
    private var temporaryWrite: (sessionID: String, changeCount: Int)?
    /// Recent clipboard revisions this manager produced, newest last.
    private var ownRevisions: [Int] = []

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var changeCount: Int {
        self.pasteboard.changeCount
    }

    func producedRevision(_ changeCount: Int) -> Bool {
        self.ownRevisions.contains(changeCount)
    }

    func holdsIntentionalText(_ text: String) -> Bool {
        guard let item = self.pasteboard.pasteboardItems?.first, self.pasteboard.pasteboardItems?.count == 1 else {
            return false
        }
        return item.string(forType: .string) == text &&
            !item.types.contains(Self.transientType) &&
            !item.types.contains(Self.sessionType)
    }

    /// Clears the pasteboard and records the revisions that produces, so a later check can
    /// tell our writes from the user's.
    @discardableResult
    private func clearOwnedContents() -> Int {
        let changeCount = self.pasteboard.clearContents()
        self.recordOwnRevision(changeCount)
        return changeCount
    }

    private func recordOwnRevision(_ changeCount: Int) {
        guard self.ownRevisions.last != changeCount else { return }
        self.ownRevisions.append(changeCount)
        if self.ownRevisions.count > 64 {
            self.ownRevisions.removeFirst(self.ownRevisions.count - 64)
        }
    }

    func captureSnapshot() -> PasteboardSnapshot? {
        let startedAt = ProcessInfo.processInfo.systemUptime
        for attempt in 1...2 {
            let startingChangeCount = self.pasteboard.changeCount
            guard let sourceItems = self.pasteboard.pasteboardItems else {
                let endingChangeCount = self.pasteboard.changeCount
                if endingChangeCount != startingChangeCount {
                    self.log("clipboard_snapshot_retry attempt=\(attempt) reason=items_unavailable_during_change")
                    continue
                }
                self.log("clipboard_snapshot_failed reason=pasteboard_items_unavailable")
                return nil
            }
            var items: [PasteboardSnapshot.Item] = []
            var totalBytes = 0
            var totalPortableImageBytes = 0
            var totalRepresentations = 0
            var skippedBytes = 0
            var skippedTypes: [String] = []
            var unreadableTypes: [String] = []

            for sourceItem in sourceItems {
                let sourceTypes = sourceItem.types
                guard !sourceTypes.isEmpty else { continue }

                var representations: [PasteboardSnapshot.Item.Representation] = []
                var skippedOversizedRepresentation = false
                representations.reserveCapacity(sourceTypes.count)
                for type in sourceTypes {
                    guard let data = sourceItem.data(forType: type) else {
                        unreadableTypes.append(type.rawValue)
                        continue
                    }
                    guard data.count <= Self.maximumRepresentationBytes else {
                        skippedOversizedRepresentation = true
                        skippedBytes += data.count
                        skippedTypes.append(type.rawValue)
                        continue
                    }
                    representations.append(.init(type: type, data: data))
                    totalBytes += data.count
                    totalRepresentations += 1
                }
                // File URLs are small references, not file contents. Preserve them and offer a
                // plain filename when a large accompanying payload was omitted.
                if skippedOversizedRepresentation,
                   !representations.contains(where: { $0.type == .string }),
                   let fileData = representations.first(where: { $0.type == .fileURL })?.data,
                   let url = URL(dataRepresentation: fileData, relativeTo: nil, isAbsolute: true),
                   url.isFileURL, !url.lastPathComponent.isEmpty
                {
                    let nameData = Data(url.lastPathComponent.utf8)
                    representations.append(.init(type: .string, data: nameData))
                    totalBytes += nameData.count
                    totalRepresentations += 1
                }
                guard !representations.isEmpty else { continue }
                let item = PasteboardSnapshot.Item(representations: representations)
                // Portable images share one budget across every item, so copying many image files
                // at once cannot balloon the snapshot.
                let imageBudget = Self.maximumRepresentationBytes - totalPortableImageBytes
                let portableImage = skippedOversizedRepresentation || imageBudget <= 0
                    ? nil
                    : Self.portableImageRepresentation(for: item, budget: imageBudget)
                totalPortableImageBytes += portableImage?.data.count ?? 0
                items.append(.init(representations: representations, portableImage: portableImage))
            }

            let endingChangeCount = self.pasteboard.changeCount
            guard endingChangeCount == startingChangeCount else {
                self.log(
                    "clipboard_snapshot_retry attempt=\(attempt) startChangeCount=\(startingChangeCount) endChangeCount=\(endingChangeCount)"
                )
                continue
            }

            self.log(
                "clipboard_snapshot_complete items=\(items.count) sourceItems=\(sourceItems.count) " +
                    "representations=\(totalRepresentations) bytes=\(totalBytes) portableImageBytes=\(totalPortableImageBytes) " +
                    "skippedBytes=\(skippedBytes) skippedTypes=\(skippedTypes.joined(separator: ",")) " +
                    "unreadableTypes=\(unreadableTypes.joined(separator: ",")) " +
                    "elapsedMs=\(Self.elapsedMs(since: startedAt)) firstItem=\(Self.representationSummary(items.first))"
            )
            return PasteboardSnapshot(items: items, wasEmpty: sourceItems.isEmpty)
        }

        self.log("clipboard_snapshot_failed reason=clipboard_changed_during_snapshot")
        return nil
    }

    func writeTemporaryText(_ text: String, sessionID: String) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string),
              item.setString(Bundle.main.bundleIdentifier ?? "com.FluidApp.app", forType: Self.sourceType),
              item.setData(Data(), forType: Self.transientType),
              item.setData(Data(), forType: Self.autoGeneratedType),
              item.setData(Data(), forType: Self.concealedType),
              item.setString(sessionID, forType: Self.sessionType)
        else {
            return false
        }

        let clearedChangeCount = self.clearOwnedContents()
        self.temporaryWrite = (sessionID, clearedChangeCount)
        let didWrite = self.pasteboard.writeObjects([item])
        self.recordOwnRevision(self.pasteboard.changeCount)
        if self.hasTemporaryText(sessionID: sessionID, expectedText: text) {
            self.temporaryWrite = (sessionID, self.pasteboard.changeCount)
            return didWrite
        }
        return false
    }

    /// An ordinary copy the user can see in clipboard history: no transient markers.
    func writeIntentionalText(_ text: String) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else { return false }
        self.clearOwnedContents()
        let didWrite = self.pasteboard.writeObjects([item])
        self.recordOwnRevision(self.pasteboard.changeCount)
        return didWrite && self.pasteboard.string(forType: .string) == text
    }

    func isOwned(sessionID: String, expectedText: String) -> Bool {
        guard let temporaryWrite,
              temporaryWrite.sessionID == sessionID,
              temporaryWrite.changeCount == self.pasteboard.changeCount
        else { return false }
        return self.hasTemporaryText(sessionID: sessionID, expectedText: expectedText)
    }

    private func hasTemporaryText(sessionID: String, expectedText: String) -> Bool {
        self.pasteboard.string(forType: .string) == expectedText &&
            self.pasteboard.string(forType: Self.sessionType) == sessionID
    }

    func restoreTemporarySnapshot(_ snapshot: PasteboardSnapshot, sessionID: String, expectedText: String) -> Bool {
        guard let temporaryWrite, temporaryWrite.sessionID == sessionID else { return false }
        return self.restore(snapshot, ifUnchangedSince: temporaryWrite.changeCount, leftoverText: expectedText)
    }

    func restore(_ snapshot: PasteboardSnapshot) -> Bool {
        self.restore(snapshot, ifUnchangedSince: nil, leftoverText: nil)
    }

    private func restore(_ snapshot: PasteboardSnapshot, ifUnchangedSince changeCount: Int?, leftoverText: String?) -> Bool {
        guard !snapshot.items.isEmpty else {
            if let changeCount, self.pasteboard.changeCount != changeCount { return false }
            if snapshot.wasEmpty {
                // The clipboard was empty before the paste; put it back that way.
                self.clearOwnedContents()
                self.log("clipboard_restore_verified items=0 reason=originally_empty")
                return true
            }
            // Every representation was too large to keep. Rather than clearing the clipboard,
            // leave the transcript on it, as an ordinary copy the user can see and paste (the
            // temporary entry is hidden from clipboard managers).
            if let leftoverText, !leftoverText.isEmpty {
                let rewritten = self.writeIntentionalText(leftoverText)
                self.log("clipboard_restore_skipped reason=nothing_captured transcriptLeftVisible=\(rewritten)")
                return rewritten
            }
            self.log("clipboard_restore_skipped reason=nothing_captured")
            return true
        }
        var items: [NSPasteboardItem] = []
        for snapshotItem in snapshot.items {
            let item = NSPasteboardItem()
            let portableImage = snapshotItem.portableImage
            let hasFileURL = snapshotItem.representations.contains { $0.type == .fileURL }

            if !hasFileURL,
               let portableImage,
               !item.setData(portableImage.data, forType: portableImage.type)
            {
                self.log("clipboard_restore_failed reason=portable_image_write_failed type=\(portableImage.type.rawValue)")
                return false
            }
            for representation in snapshotItem.representations {
                guard Self.writeRestoredRepresentation(representation, to: item) else {
                    self.log("clipboard_restore_failed reason=representation_write_failed type=\(representation.type.rawValue)")
                    return false
                }
                if representation.type == .fileURL,
                   let portableImage,
                   !item.setData(portableImage.data, forType: portableImage.type)
                {
                    self.log("clipboard_restore_failed reason=portable_image_write_failed type=\(portableImage.type.rawValue)")
                    return false
                }
            }
            guard Self.addRestorationMarkers(to: item) else {
                self.log("clipboard_restore_failed reason=marker_write_failed")
                return false
            }
            items.append(item)
        }

        // Recheck after preparing representations; a newer external copy wins.
        if let changeCount, self.pasteboard.changeCount != changeCount {
            self.log("clipboard_restore_skipped reason=clipboard_changed_since_paste")
            return false
        }
        self.clearOwnedContents()
        let didWrite = self.pasteboard.writeObjects(items)
        self.recordOwnRevision(self.pasteboard.changeCount)
        guard didWrite else {
            self.log("clipboard_restore_failed reason=pasteboard_write_failed")
            return false
        }
        guard self.containsRestoredSnapshot(snapshot) else {
            self.log("clipboard_restore_failed reason=post_write_verification_failed")
            return false
        }

        self.log(
            "clipboard_restore_verified items=\(snapshot.items.count) changeCount=\(self.pasteboard.changeCount) " +
                "firstItem=\(Self.representationSummary(snapshot.items.first)) " +
                "portableImageBytes=\(snapshot.items.first?.portableImage?.data.count ?? 0)"
        )
        return true
    }

    private func containsRestoredSnapshot(_ snapshot: PasteboardSnapshot) -> Bool {
        let restoredItems = self.pasteboard.pasteboardItems ?? []
        guard restoredItems.count == snapshot.items.count else { return false }

        for (restoredItem, snapshotItem) in zip(restoredItems, snapshot.items) {
            for representation in snapshotItem.representations {
                if representation.type == .fileURL,
                   restoredItem.data(forType: .fileURL) == nil,
                   snapshotItem.portableImage != nil
                {
                    continue
                }
                guard Self.restoredData(restoredItem, matches: representation) else {
                    return false
                }
            }
            if let portableImage = snapshotItem.portableImage,
               restoredItem.data(forType: portableImage.type) != portableImage.data
            {
                return false
            }
            guard restoredItem.types.contains(Self.transientType),
                  restoredItem.types.contains(Self.autoGeneratedType)
            else {
                return false
            }
        }
        return true
    }

    private static func restoredData(
        _ restoredItem: NSPasteboardItem,
        matches representation: PasteboardSnapshot.Item.Representation
    ) -> Bool {
        if representation.type == .fileURL,
           let expectedURL = URL(dataRepresentation: representation.data, relativeTo: nil, isAbsolute: true),
           let restoredURL = restoredItem.string(forType: .fileURL).flatMap(URL.init(string:))
        {
            return restoredURL == expectedURL
        }
        return restoredItem.data(forType: representation.type) == representation.data
    }

    private static func portableImageRepresentation(
        for item: PasteboardSnapshot.Item,
        budget: Int
    ) -> PasteboardSnapshot.Item.Representation? {
        let sourceTypes = Set(item.representations.map(\.type))
        guard !sourceTypes.contains(.png),
              !sourceTypes.contains(.tiff)
        else {
            return nil
        }

        if !sourceTypes.isDisjoint(with: Self.fileSemanticTypes) {
            guard Self.fileItemContainsImage(item) else { return nil }

            // Preserve an image file's encoded bytes directly. Decoding and re-encoding it here
            // would put work proportional to its pixel count on the paste critical path.
            if let fileURL = Self.fileURL(in: item),
               let fileType = UTType(filenameExtension: fileURL.pathExtension),
               fileType.conforms(to: .image),
               Self.isReadableLocalFile(fileURL, maximumBytes: budget),
               let imageData = try? Data(contentsOf: fileURL, options: .mappedIfSafe)
            {
                return .init(
                    type: NSPasteboard.PasteboardType(fileType.identifier),
                    data: imageData
                )
            }
        }

        for representation in item.representations {
            guard UTType(representation.type.rawValue)?.conforms(to: .image) == true,
                  representation.data.count <= Self.maximumPortableImageSourceBytes,
                  let pngData = Self.pngData(from: representation.data),
                  pngData.count <= budget
            else {
                continue
            }
            return .init(type: .png, data: pngData)
        }
        return nil
    }

    /// Only local, already-downloaded files under the size cap are read on the paste path: an
    /// iCloud placeholder or a network volume could otherwise stall the paste.
    private static func isReadableLocalFile(_ url: URL, maximumBytes: Int) -> Bool {
        let keys: Set<URLResourceKey> = [.fileSizeKey, .volumeIsLocalKey, .isUbiquitousItemKey, .ubiquitousItemDownloadingStatusKey]
        guard url.isFileURL, let values = try? url.resourceValues(forKeys: keys) else { return false }
        guard let size = values.fileSize, size <= min(maximumBytes, self.maximumRepresentationBytes) else { return false }
        if values.volumeIsLocal == false { return false }
        if values.isUbiquitousItem == true, values.ubiquitousItemDownloadingStatus != .current { return false }
        return true
    }

    private static func fileItemContainsImage(_ item: PasteboardSnapshot.Item) -> Bool {
        if let fileURL = self.fileURL(in: item),
           self.isImageFilename(fileURL.lastPathComponent)
        {
            return true
        }

        guard let textRepresentation = item.representations.first(where: { $0.type == .string }),
              let filename = String(data: textRepresentation.data, encoding: .utf8)
        else {
            return false
        }
        return self.isImageFilename(filename)
    }

    private static func fileURL(in item: PasteboardSnapshot.Item) -> URL? {
        guard let representation = item.representations.first(where: { $0.type == .fileURL }) else {
            return nil
        }
        return URL(dataRepresentation: representation.data, relativeTo: nil, isAbsolute: true)
    }

    private static func isImageFilename(_ filename: String) -> Bool {
        let pathExtension = (filename as NSString).pathExtension
        return !pathExtension.isEmpty && UTType(filenameExtension: pathExtension)?.conforms(to: .image) == true
    }

    private static func writeRestoredRepresentation(
        _ representation: PasteboardSnapshot.Item.Representation,
        to item: NSPasteboardItem
    ) -> Bool {
        if representation.type == .fileURL,
           let fileURL = URL(dataRepresentation: representation.data, relativeTo: nil, isAbsolute: true)
        {
            // A file URL is a semantic pasteboard property-list value. Re-emitting its opaque
            // bytes can appear valid to this process while disappearing for readers.
            return item.setString(fileURL.absoluteString, forType: .fileURL)
        }
        return item.setData(representation.data, forType: representation.type)
    }

    private static func pngData(from sourceData: Data) -> Data? {
        if let bitmap = NSBitmapImageRep(data: sourceData) {
            return bitmap.representation(using: .png, properties: [:])
        }

        guard let image = NSImage(data: sourceData) else { return nil }
        var proposedRect = NSRect(origin: .zero, size: image.size)
        guard let cgImage = image.cgImage(forProposedRect: &proposedRect, context: nil, hints: nil) else {
            return nil
        }
        return NSBitmapImageRep(cgImage: cgImage).representation(using: .png, properties: [:])
    }

    /// Restored items carry the transient markers so clipboard managers do not record the
    /// user's own content a second time; they are deliberately not concealed.
    private static func addRestorationMarkers(to item: NSPasteboardItem) -> Bool {
        let transientWasWritten = item.types.contains(Self.transientType) ||
            item.setData(Data(), forType: Self.transientType)
        let autoGeneratedWasWritten = item.types.contains(Self.autoGeneratedType) ||
            item.setData(Data(), forType: Self.autoGeneratedType)
        return transientWasWritten && autoGeneratedWasWritten
    }

    private static func representationSummary(_ item: PasteboardSnapshot.Item?) -> String {
        guard let item else { return "none" }
        return item.representations
            .map { "\($0.type.rawValue):\($0.data.count)" }
            .joined(separator: ",")
    }

    /// A few lines per paste, kept in Release: clipboard snapshot, restore and backup outcomes
    /// are what an agent needs to diagnose a clobbered clipboard in the installed app.
    private func log(_ message: @autoclosure () -> String) {
        DeliveryLog.info(message(), source: "ClipboardPasteSession")
    }

    private static func elapsedMs(since start: TimeInterval) -> Int {
        Int(((ProcessInfo.processInfo.systemUptime - start) * 1000).rounded())
    }
}

/// Owns the pasteboard for one clipboard paste at a time: snapshot, temporary write, paste,
/// then restore once the target has had time to read it. Transcript backups after a failed
/// delivery go through the same gate, so a pending restore can never undo a backup, and
/// neither can overwrite something the user copied in the meantime.
nonisolated final class ClipboardPasteSession: @unchecked Sendable {
    static let shared = ClipboardPasteSession(pasteboard: SystemPasteboardManager())

    private let pasteboard: PasteboardManaging
    private let gate = DispatchSemaphore(value: 1)
    private let restoreQueue: DispatchQueue
    private let backupQueue: DispatchQueue

    init(pasteboard: PasteboardManaging, label: String = "ClipboardPasteSession") {
        self.pasteboard = pasteboard
        self.restoreQueue = DispatchQueue(label: "\(label).Restore", qos: .utility)
        self.backupQueue = DispatchQueue(label: "\(label).Backup", qos: .userInitiated)
    }

    var changeCount: Int {
        self.pasteboard.changeCount
    }

    /// Runs one paste. Blocks while an earlier session still owns the pasteboard, so call it
    /// off the main thread.
    ///
    /// - Parameters:
    ///   - dispatch: posts the paste command and reports whether it did.
    ///   - makeConsumptionWait: called while this session owns the pasteboard, after the
    ///     transcript is on it and just before `dispatch`, so any baseline it reads (the field's
    ///     text, say) is taken after earlier pastes have landed. It returns the wait that runs on
    ///     the restore queue; the original clipboard comes back once that wait returns.
    /// - Returns: nil when the paste command was dispatched.
    func paste(
        _ text: String,
        dispatch: () -> Bool,
        makeConsumptionWait: () -> () -> Void
    ) -> TextDeliveryFailure? {
        self.gate.wait()
        var releasesGateOnReturn = true
        defer {
            if releasesGateOnReturn { self.gate.signal() }
        }

        guard let snapshot = self.pasteboard.captureSnapshot() else {
            self.log("paste_session_failed reason=clipboard_snapshot_failed")
            return .clipboardSnapshotFailed
        }

        let sessionID = UUID().uuidString
        guard self.pasteboard.writeTemporaryText(text, sessionID: sessionID) else {
            // A partial write may have cleared the board without installing our text. Restore
            // that revision if it is still ours; a newer copy is left alone.
            _ = self.pasteboard.restoreTemporarySnapshot(snapshot, sessionID: sessionID, expectedText: text)
            self.log("paste_session_failed reason=clipboard_write_failed")
            return .clipboardWriteFailed
        }

        let consumptionWait = makeConsumptionWait()
        guard dispatch() else {
            _ = self.pasteboard.restoreTemporarySnapshot(snapshot, sessionID: sessionID, expectedText: text)
            self.log("paste_session_failed reason=paste_command_failed")
            return .pasteCommandFailed
        }
        StopPathTrace.current?.mark(.pastePosted)

        releasesGateOnReturn = false
        self.restoreQueue.async {
            defer { self.gate.signal() }
            consumptionWait()
            let restored = self.pasteboard.restoreTemporarySnapshot(snapshot, sessionID: sessionID, expectedText: text)
            self.log(restored ? "paste_session_restored" : "paste_session_not_restored")
        }
        return nil
    }

    /// Puts the transcript on the clipboard as an ordinary copy (visible in clipboard history)
    /// after a failed or unconfirmed delivery. Waits for any paste still holding the pasteboard.
    ///
    /// The write only happens when every clipboard change since `revision` was Liquid Voice's own
    /// (a paste, a restore, an earlier backup): anything the user copied since is never replaced.
    /// `revision` defaults to the clipboard as it is now; pass the revision seen when the problem
    /// started (for example right after the paste a read-back later found missing).
    /// `completion` reports what happened.
    func keepTranscript(
        _ text: String,
        since revision: Int? = nil,
        completion: (@Sendable (TranscriptBackupOutcome) -> Void)? = nil
    ) {
        guard !text.isEmpty else {
            completion?(.emptyText)
            return
        }
        let observedChangeCount = revision ?? self.pasteboard.changeCount
        self.backupQueue.async {
            self.gate.wait()
            defer { self.gate.signal() }
            let current = self.pasteboard.changeCount
            guard Self.onlyOwnChanges(since: observedChangeCount, through: current, pasteboard: self.pasteboard) else {
                self.log("transcript_backup_skipped reason=newer_clipboard_copy")
                completion?(.newerClipboardCopy)
                return
            }
            if self.pasteboard.holdsIntentionalText(text) {
                self.log("transcript_backup_skipped reason=already_on_clipboard")
                completion?(.alreadyOnClipboard)
                return
            }
            let copied = self.pasteboard.writeIntentionalText(text)
            self.log("transcript_backup success=\(copied) chars=\(text.count)")
            completion?(copied ? .copied : .writeFailed)
        }
    }

    private static func onlyOwnChanges(since observed: Int, through current: Int, pasteboard: PasteboardManaging) -> Bool {
        guard current >= observed else { return false }
        guard current > observed else { return true }
        // Each clipboard change bumps the count by one; every step since must be ours.
        return (observed + 1...current).allSatisfy { pasteboard.producedRevision($0) }
    }

    /// Waits until every scheduled restore and backup has finished. For tests.
    func waitUntilIdle() {
        self.restoreQueue.sync {}
        self.backupQueue.sync {}
        self.gate.wait()
        self.gate.signal()
    }

    /// A few lines per paste, kept in Release: clipboard snapshot, restore and backup outcomes
    /// are what an agent needs to diagnose a clobbered clipboard in the installed app.
    private func log(_ message: @autoclosure () -> String) {
        DeliveryLog.info(message(), source: "ClipboardPasteSession")
    }
}

/// The synthesized paste keystrokes.
nonisolated enum PasteCommandEvents {
    /// Marks events Liquid Voice synthesized, so its own hotkey tap passes them through.
    static let synthesizedEventUserData: Int64 = 0x46565353

    /// Global paste through the HID stream: Command down, V down, V up, Command up. Pressing and
    /// releasing Command explicitly matters: setting the flag on V alone leaves the HID state
    /// reporting Command as held until the next real key event.
    static func makeGlobalPasteEvents(pasteKeyCode: CGKeyCode) -> [CGEvent] {
        let commandKeyCode = CGKeyCode(kVK_Command)
        let source = CGEventSource(stateID: .combinedSessionState)
        guard let cmdDown = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: true),
              let vDown = CGEvent(keyboardEventSource: source, virtualKey: pasteKeyCode, keyDown: true),
              let vUp = CGEvent(keyboardEventSource: source, virtualKey: pasteKeyCode, keyDown: false),
              let cmdUp = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: false)
        else {
            return []
        }

        cmdDown.flags = .maskCommand
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand
        cmdUp.flags = []
        let events = [cmdDown, vDown, vUp, cmdUp]
        events.forEach(self.markSynthesized)
        return events
    }

    /// Paste sent straight to one process (the c11/Ghostty path). These events never enter the
    /// HID stream, so they cannot leave Command held system-wide; the pair is kept exactly as
    /// it has been proven in c11, only tagged as synthesized.
    static func makeTargetedPasteEvents(pasteKeyCode: CGKeyCode) -> [CGEvent] {
        guard let vDown = CGEvent(keyboardEventSource: nil, virtualKey: pasteKeyCode, keyDown: true),
              let vUp = CGEvent(keyboardEventSource: nil, virtualKey: pasteKeyCode, keyDown: false)
        else {
            return []
        }
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand
        let events = [vDown, vUp]
        events.forEach(self.markSynthesized)
        return events
    }

    static func isSynthesized(_ event: CGEvent) -> Bool {
        event.getIntegerValueField(.eventSourceUserData) == self.synthesizedEventUserData
    }

    private static func markSynthesized(_ event: CGEvent) {
        event.setIntegerValueField(.eventSourceUserData, value: self.synthesizedEventUserData)
    }
}
